version: "3"
    
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - database:/var/lib/mysql    
  
  php:
    image: php:7.2-apache
    ports: 
      - "80:80"
    volumes:
       - ./www:/var/www/html/
         
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8765:80"
    depends_on:
      - "db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass    

volumes:
  database:


